<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7ehib4i\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7ehib4i/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container7ehib4i.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container7ehib4i\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container7ehib4i\appDevDebugProjectContainer([
    'container.build_hash' => '7ehib4i',
    'container.build_id' => '9727fdd9',
    'container.build_time' => 1581504720,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7ehib4i');
