<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAjfel36\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAjfel36/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAjfel36.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAjfel36\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerAjfel36\appDevDebugProjectContainer([
    'container.build_hash' => 'Ajfel36',
    'container.build_id' => '614b2c08',
    'container.build_time' => 1581463539,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAjfel36');
