<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLlexisa\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLlexisa/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerLlexisa.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerLlexisa\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerLlexisa\appDevDebugProjectContainer([
    'container.build_hash' => 'Llexisa',
    'container.build_id' => '6ecb64e3',
    'container.build_time' => 1581250545,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLlexisa');
